config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/pricing', to: 'pages#pricing', as: :pricing
  get '/how-it-works', to: 'pages#how_it_works', as: :how_it_works
  get '/support', to: 'pages#support', as: :support

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :pricing, :how_it_works, :support ]

  def home
    @customers = Customer.all
  end

  def pricing
  end

  def how_it_works
  end

  def support
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_infinite_slide.html.erb
<div class="slider">
	<div class="slide-track">
		<div class="slide">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/1.png" height="100" width="250" alt="" />
		</div>
		<div class="slide">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/2.png" height="100" width="250" alt="" />
		</div>
		<div class="slide">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/3.png" height="100" width="250" alt="" />
		</div>
		<div class="slide">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/4.png" height="100" width="250" alt="" />
		</div>
		<div class="slide">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/5.png" height="100" width="250" alt="" />
		</div>
		<div class="slide">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/6.png" height="100" width="250" alt="" />
		</div>
		<div class="slide">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/7.png" height="100" width="250" alt="" />
		</div>
		<div class="slide">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/1.png" height="100" width="250" alt="" />
		</div>
		<div class="slide">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/2.png" height="100" width="250" alt="" />
		</div>
		<div class="slide">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/3.png" height="100" width="250" alt="" />
		</div>
		<div class="slide">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/4.png" height="100" width="250" alt="" />
		</div>
		<div class="slide">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/5.png" height="100" width="250" alt="" />
		</div>
		<div class="slide">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/6.png" height="100" width="250" alt="" />
		</div>
		<div class="slide">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/7.png" height="100" width="250" alt="" />
		</div>
	</div>
</div>

app/views/layouts/_pricing-card.html.erb
<div class="pricing-card <%= central %>">
  <h1><strong><%= offer %></strong></h1>
  <h2><span class="price">$<%= price[0] %></span> per month</h2>
  <h3>+<span class="price">$<%= price[1] %></span><span> per additional location</span></h3>
  <div class="features-list">
    <ul>
      <li class=<%= options[0] %>>Capture dine-in experiences</li>
      <li class=<%= options[1] %>>Capture delivery experiences</li>
      <li class=<%= options[2] %>>Unlimited reviews</li>
      <li class=<%= options[3] %>>Unlimited users</li>
      <li class=<%= options[4] %>>Get customer contact details</li>
      <li class=<%= options[5] %>>Compare multiple venues</li>
      <li class=<%= options[6] %>>Customize design</li>
      <li class=<%= options[7] %>>Customize survey questions</li>
    </ul>
  </div>
  <div>
    <%= link_to  "30 days free trial", :root, class:"button" %>
  </div>
</div>

app/views/layouts/_testimonial.html.erb
<% @customers.each do |customer| %>
  <div class="grid swiper-slide">
    <div class="column c-details">
      <%= image_tag customer.logo_url, class:"c-logo"%>
      <p>
        <strong><%= customer.name %>,
        <br>
        </strong><%= customer.job_title %> at <%= customer.company %>
      </p>
    </div>
    <div class="column c-picture">
      <%= image_tag customer.picture_url %>
    </div>
    <div class="column c-testimonial">
      <%= image_tag "quote.png" %>
      <p>
        <%= customer.testimonial %>
      </p>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TablevibeRedesign</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="home">
  <div class="home-card" id="banner">
    <div class="content">
      <h1>The #1 platform for restaurants to <strong>capture feedback, drive satisfaction</strong> and <strong>accelerate direct sales.</strong></h1>
      <div class="button-wrapper">
        <%= link_to  "Get started for free!", :root, class:"button button-outline" %>
        <%= link_to  "Book a demo", :root, class:"button" %>
      </div>
    </div>
    <div class="img-wrapper">
      <%= image_tag "banner-phone.png" %>
    </div>
  </div>
  <div id="customers">
    <h3>Generated over 120.000 customer insights for leading restaurants globally</h3>
    <%= render  "layouts/infinite_slide" %>
  </div>
  <div class="home-card revert">
    <div class="img-wrapper">
      <%= image_tag "delivery-gift.png"%>
    </div>
    <div class="content">
      <h2><strong>Capture dine-in and delivery feedback</strong></h2>
      <p>Your dine-in and delivery customers complete a fun, 1-minute feedback survey on their phone. In return they get a loyalty incentive to be redeemed for a commission free dine-in or pickup order.</p>
    </div>
  </div>
  <div data-controller="carousel" class="swiper-container w-25 my-5"
    data-carousel-options-value='{
    "autoplay": { "delay": 2500,
                "disableOnInteraction": "false"},
    "pagination": { "el": ".swiper-pagination",
                    "dynamicBullets": "true" },
    "navigation": { "nextEl": ".swiper-button-next",
                    "prevEl": ".swiper-button-prev"}}'>
    <!-- Pagination (... or 1/10 or progress bar) -->
    <div class="swiper-pagination"></div>

  <!-- Navigation buttons (< >) -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
    <div class="swiper-wrapper">
    <!-- Slides -->
      <%= render  'layouts/testimonial', customers: @customers %>
    </div>
  </div>
  <div class="home-card">
    <div class="content">
      <h2><strong>Learn what makes your guests happy</strong></h2>
      <p>All your customer feedback shows up in a simple-to-use performance dashboard. Understand which venues and waiters do well and directly contact customers to learn more. Act on feedback and see your customer ratings improve over time.</p>
      <%= link_to  "See demo dashboard!", :root, class:"button" %>
    </div>
    <div class="img-wrapper">
      <%= image_tag "dashboard.png"%>
    </div>
  </div>
  <div id="grow">
    <%= image_tag "burger.png", class:"section-img"%>
    <h2 class="section-title">Grow direct revenue</h2>
    <div class="cards">
      <div class="card">
        <%= image_tag "moneybag.png"%>
        <h3><strong>Save up to 40% in delivery commissions</strong></h3>
        <p>Put a Tablevibe QR code on your food delivery packages to unlock customer data and accelerate direct re-orders.</p>
      </div>
      <div class="card">
        <%= image_tag "spaceship.png"%>
        <h3><strong>Boost repeat business</strong></h3>
        <p>In return for their honest feedback, customers get a reward for their next order or visit. We delivered 1000s of repeat customers to existing partners</p>
      </div>
      <div class="card">
        <%= image_tag "google-logo.png"%>
        <h3><strong>Get better Google reviews</strong></h3>
        <p>Improve your online reputation by encouraging positive guests to share their feedback directly on Google</p>
      </div>
    </div>
    <div class="cta">
      <%= link_to  "Get started for free", :root, class:"button" %>
      <%= link_to  "Book a demo", :root, class:"button button-outline" %>
    </div>
  </div>
  <div id="partners">
    <div class="section-intro">
      <%= image_tag "cheesecake.png", class:"section-img"%>
      <h2 class="section-title">Committed to product excellence together with our valued partners</h2>
    </div>
    <div class="partner-links">
      <%= link_to "https://www.ycombinator.com/companies/tablevibe-co", class: "column", target:"_blanck" do%>
        <%= image_tag "ycombinator.png", height:"50px"  %>
      <% end %>
      <%= link_to "https://get.apicbase.com/", class: "column", target:"_blanck" do%>
        <%= image_tag "apicbase.png", height:"50px" %>
      <% end %>
      <%= link_to "https://cloud.google.com/", class: "column", target:"_blanck" do%>
        <%= image_tag "googlecloud.png", height:"50px" %>
      <% end %>
      <%= link_to "https://landing.qr-code-generator.com/18e96a3e-6679-4cb7-9e76-59f5f9c9766f", class: "column", target:"_blanck" do%>
        <%= image_tag "qrcodegenerator.png", height:"50px" %>
      <% end %>
      <%= link_to "https://www.hubspot.com/startups", class: "column", target:"_blanck" do%>
        <%= image_tag "hubspot.png", height:"50px" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/how_it_works.html.erb
<div id="how-it-works">
  <div id="title">
    <h1>How it works</h1>
    <p>Tablevibe helps you own and grow your customer relationships in minutes. It can be used on a self-serve basis and does not require any technical implementation</p>
    <%= image_tag "woman-missile.svg" %>
  </div>
  <div id="explanations">
  <%# Step 1 %>
    <div class="row row-step">
      <div class="step-number">
        <%= image_tag "number1.png"%>
      </div>
      <div class="step-box-wrapper">
        <h2>Get started</h2>
        <p>Sign up to experience the benefits of Tablevibe. We offer relevant solutions for restaurants and cloud kitchens of any size.</p>
      </div>
      <div class="curly-lines">
        <%= image_tag "curly-lines-lr.svg"%>
      </div>
    </div>
    <%# Step 2 %>
    <div class="row row-step right">
      <div class="step-number">
        <%= image_tag "number2.png"%>
      </div>
      <div class="step-two-rows">
        <div class="step-box-wrapper">
          <h2>Experience types</h2>
          <p>Select if you would like to capture feedback from dine-in, delivery or both types of customers. Your surveys will be up an running in seconds!</p>
        </div>
        <div class="step-box-bottom-wrapper row">
            <div class="step-box-bottom">
              <%= image_tag "cutlery.svg" %>
              <p>Dine in</p>
            </div>
            <div class="step-box-bottom">
              <%= image_tag "scooter.svg" %>
              <p>Delivery</p>
            </div>
        </div>
        <div class="curly-lines right">
          <%= image_tag "curly-lines-rl.svg"%>
        </div>
      </div>
    </div>
    <%# Step 3 %>
    <div class="row row-step">
      <div class="step-number">
        <%= image_tag "number3.png"%>
      </div>
      <div class="step-box-wrapper">
        <h2>Define your reward</h2>
        <p>
          You decide what reward your customers receive in exchange for their feedback. Popular options include “$5 off on your next visit” and “10% discount on any new takeaway order”.
          <br>
          Reward conditions are often used to drive traffic to your restaurant during off-peak hours or promote direct orders. In example: “Reward is valid Mon-Thu” or “Reward is valid for takeaway orders”.
        </p>
        <div class="step-box-img">
          <%= image_tag "gift.png", id:"gift-icon" %>
        </div>
      </div>
      <div class="curly-lines">
        <%= image_tag "curly-lines-lr.svg", id:"curly3"%>
      </div>
    </div>
    <%# Step 4 %>
    <div class="row row-step right">
      <div class="step-number">
        <%= image_tag "number4.png"%>
      </div>
      <div class="step-box-wrapper">
        <h2>
          Invite customers
          <br>
          to share feedback
        </h2>
        <p>
          Simply add a Tablevibe QR code on your food delivery packages or present it to your dine-in customers. Completing the survey takes 1minute. Positive customers are prompted to share their feedback on Google. It's a great way to capture feedback and boost your online reputation at the same time.
        </p>
        <div class="step-box-img">
          <%= image_tag "delivery.png", id:"delivery-icon" %>
        </div>
        <div class="curly-lines right">
          <%= image_tag "curly-lines-rl.svg"%>
        </div>
      </div>
    </div>
    <%# Step 5 %>
    <div class="row row-step">
      <div class="step-number">
        <%= image_tag "number5.png"%>
      </div>
      <div class="step-box-wrapper">
        <h2>Drive customer satisfaction</h2>
        <p>
          All your customer feedback shows up in an easy-to-use performance dashboard. Understand which venues and waiters do well and directly contact customers to learn more.
          <br>
          <br>
          Act on the insights and see your customer ratings improve over time. You can also add customer email addresses to your email marketing lists.
        </p>
        <div class="step-box-img">
          <%= image_tag "dashboard-small.png", id:"dashboard-icon" %>
        </div>
      </div>
      <div class="curly-lines">
        <%= image_tag "curly-lines-lr.svg", id:"curly5"%>
      </div>
    </div>
    <%# Step 6 %>
    <div class="row row-step right">
      <div class="step-number">
        <%= image_tag "number6.png"%>
      </div>
      <div class="step-box-wrapper">
        <h2>Redeem loyalty rewards</h2>
        <p>
          Customers receive a reward voucher via email upon survey completion. You decide when and where customers can redeem their reward.
          <br>
          <br>
          You can share a discount code for your preferred online ordering portal. To redeem a dine-in reward, simply scan the reward voucher in the email with any phone or tablet. Your waiters can also see what feedback the customer provided and follow up on any compliments or suggestions.
        </p>
      </div>
    </div>
    <div class="row row-cta">
      <div id="call-to-action">
        <h2>Get started with Tablevibe today!</h2>
        <p>
          We will have your surveys up and running in minutes. If you have any
          <br>
          more questions please don't hesitate to reach out or book a demo.</p>
        <div class="button-wrapper">
          <%= link_to  "Get started for free!", :root, class:"button" %>
          <%= link_to  "Book a demo", :root, class:"button button-outline " %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/pricing.html.erb
<div id="pricing">
  <div id="title">
    <div class="over">
      <%= image_tag "burger.png" %>
    </div>
    <h1>Plans to suit <strong>any</strong><br>type of <strong>restaurant</strong></h1>
    <h3>Try 30 days for free. Cancel or change your plan any time.</h3>
    <div class="under">
      <%= image_tag "pizza.png" %>
    </div>
  </div>
  <div id="subscription">
    <div class="valuepack">
      <%= image_tag "valuepack.svg" %>
    </div>
    <div class="grid-sub">
      <%= render  "layouts/pricing-card", price: [59, 39], offer: "Dine in",
      options: ["check", "cross", "check", "check", "check", "check", "check", "check"], central: "" %>
      <%= render  "layouts/pricing-card", price: [79, 59], offer: "Dine in & Delivery",
      options: ["check", "check", "check", "check", "check", "check", "check", "check"], central: "central-card" %>
      <%= render  "layouts/pricing-card", price: [59, 39], offer: "Delivery",
      options: ["cross", "check", "check", "check", "check", "check", "check", "check"], central: "" %>
    </div>
  </div>
</div>

app/views/pages/support.html.erb
<div id="support">
  <%# Intro/ title %>
  <div id="title">
    <div class="row">
      <h1>Frequently Asked Questions</h1>
      <div class="title-img">
        <%= image_tag "question-mark.svg" %>
      </div>
    </div>
  </div>
  <%# Q&A main wrapper %>
  <div class="q-and-a-main-wrapper">
    <%# GETTING STARTED %>
    <div class="q-and-a-cat-wrapper">
      <h2>Getting Started</h2>
      <div class="toggle-wrapper">
        <button type="button" class="collapsible">How long is the free trial period?</button>
        <div class="collapsible-content">
          <p>You will get a 30 day free trial for your first subscription.</p>
        </div>
      </div>
      <div class="toggle-wrapper">
        <button type="button" class="collapsible">How do I add a new venue?</button>
        <div class="collapsible-content">
          <p>Simply log in to your Tablevibe account, select Surveys>QR codes. There you can add a new venue.</p>
        </div>
      </div>
      <div class="toggle-wrapper">
        <button type="button" class="collapsible">How do I change details of my staff members?</button>
        <div class="collapsible-content">
          <p>Simply log in to your Tablevibe account. Toggle to the dine-in experience on the top right hand corner and select Surveys>Settings>Staff Members. Here you can add staff members and add them to each venue.</p>
        </div>
      </div>
    </div>
    <%# USING TABLEVIBE %>
    <div class="q-and-a-cat-wrapper">
      <h2>Using Tablevibe</h2>
      <div class="toggle-wrapper">
        <button type="button" class="collapsible">How many venues can I add to Tablevibe?</button>
        <div class="collapsible-content">
          <p>You can add as many venues as you like. You are being billed per venue at a discounted rate for each additional venue.</p>
        </div>
      </div>
      <div class="toggle-wrapper">
        <button type="button" class="collapsible">Where can I find your terms and conditions?</button>
        <div class="collapsible-content">
          <p>Please find our terms and conditions on <%= link_to "www.tablevibe.co/terms.", :root %></p>
        </div>
      </div>
      <div class="toggle-wrapper">
        <button type="button" class="collapsible">How can I reset or change my password?</button>
        <div class="collapsible-content">
          <p>Visit <%= link_to "www.tablevibe.co/login", new_user_session_path %>, click on “Forgot your password?” and follow the instructions. If you’re logged in, please log out first before visiting <%= link_to "www.tablevibe.co/login", new_user_session_path %></p>
        </div>
      </div>
    </div>
    <%# Account, subscription and invoices %>
    <div class="q-and-a-cat-wrapper">
      <h2>Account, subscription and invoices</h2>
      <div class="toggle-wrapper">
        <button type="button" class="collapsible">When will I be billed?</button>
        <div class="collapsible-content">
          <p>You are offered a standard 30-day free trial which can be cancelled at any time by visiting Account>Subscription. After your free trial you will be billed for the first month. Your subscription will get renewed and billed automatically using this same cadence.</p>
        </div>
      </div>
      <div class="toggle-wrapper">
        <button type="button" class="collapsible">How will I get billed if my subscription changes half way through a billing cycle (i.e. by adding venues or upgrading)</button>
        <div class="collapsible-content">
          <p>
            You will only be charged for the time you use our products. Tablevibe automatically calculates the days remaining on your billing cycle and charges you on a prorated basis. These pro-rated costs will be billed directly. See examples below.
            <br>
            Monthly billing example: Your billing cycle starts on May 30th. You add a new venue to your delivery & dine-in account on May 15th. This means you will receive a one-off charge of $59*(15/30)=$29.50. Your next billing cycle automatically includes the new venue.
          </p>
        </div>
      </div>
      <div class="toggle-wrapper">
        <button type="button" class="collapsible">What payment options does Tablevibe offer?</button>
        <div class="collapsible-content">
          <p>Tablevibe offers all major credit and debit cards. We currently do not support wire transfers or direct debit payment options by default. If this is an issue to you, please contact No one, because this is not the real website ;); we’re happy to evaluate if we can accommodate your preferred payment type.</p>
        </div>
      </div>
      <div class="toggle-wrapper">
        <button type="button" class="collapsible">How do I switch between plans?</button>
        <div class="collapsible-content">
          <p>Currently it is possible to upgrade to both experience types or cancel your subscription under Account>subscription. You can also remove venues from your account under Survey>QR codes. These will no longer be billed on your next billing cycle. If you wish to switch plans please reach out to No one, because this is not the real website ;)</p>
        </div>
      </div>
    </div>
    <%# Best practices %>
    <div class="q-and-a-cat-wrapper">
      <h2>Best practices</h2>
      <div class="toggle-wrapper">
        <button type="button" class="collapsible">What is a good rating?</button>
        <div class="collapsible-content">
          <p>We generally consider a 5/5 star rating a good rating. This is why only guests who provide a 5 star overall rating have the option to leave a Google review via the Tablevibe survey.</p>
        </div>
      </div>
      <div class="toggle-wrapper">
        <button type="button" class="collapsible">What is a good incentive?</button>
        <div class="collapsible-content">
          <p>The best converting incentives are absolute discounts (i.e. $5 discount).</p>
        </div>
      </div>
      <div class="toggle-wrapper">
        <button type="button" class="collapsible">What is a good QR card?</button>
        <div class="collapsible-content">
          <p>A good QR card mentions the incentive clearly and is displayed in a prominent place. Make sure that the QR code does not have to be broken to unwrap the food.</p>
        </div>
      </div>
      <div class="toggle-wrapper">
        <button type="button" class="collapsible">What is a good response rate?</button>
        <div class="collapsible-content">
          <p>We see response rates typically vary between 5-25% depending on the incentive, the messaging and the commitment from your staff to call out the gift waiting for them.</p>
        </div>
      </div>
      <div class="toggle-wrapper">
        <button type="button" class="collapsible">Any other questions?</button>
        <div class="collapsible-content">
          <p>If you have further questions or concerns, please do not hesitate to reach us via email at Noone.com, because this is not the real website ;) or by clicking the support chat box on the lower right side of your screen.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row row-cta">
      <div id="call-to-action">
        <h2>Get started with Tablevibe today!</h2>
        <p>
          We will have your surveys up and running in minutes. If you have any
          <br>
          more questions please don't hesitate to reach out or book a demo.</p>
        <div class="button-wrapper">
          <%= link_to  "Get started for free!", :root, class:"button" %>
          <%= link_to  "Book a demo", :root, class:"button button-outline " %>
        </div>
        <%= image_tag "woman-phone.png" %>
      </div>
    </div>
</div>
<%= javascript_pack_tag 'collapsible' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer">
  <div class="inner">
    <div class="top">
      <%# Logo link to home %>
      <%= link_to :root, id:"link-home" do %>
        <%= image_tag "logo.png", class:"navbar-logo" %>
      <% end %>
      <%# navigation links %>
      <div class="nav-links">
        <%= link_to  "How it works", :root, class:"button button-clear" %>
        <%= link_to  "Pricing", :root, class:"button button-clear" %>
        <%= link_to  "Updates", :root, class:"button button-clear" %>
        <%= link_to  "Support", :root, class:"button button-clear" %>
      </div>
    </div>
    <div class="bottom">
      <p>©Tablevibe. All rights reserved</p>
      <p>This is a copy of ©Tablevibe website created for personal purpose and display on developer portfolio.</p>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div id="navbar-sm">
  <div class="nav-wrapper">
    <%# Logo link to home %>
    <%= link_to :root, id:"link-home" do %>
      <%= image_tag "logo.png", class:"navbar-logo" %>
    <% end %>
    <div class="toggle-menu", onclick="this.nextElementSibling.classList.toggle('toggle');">
      <div class="line line1"></div>
      <div class="line line2"></div>
      <div class="line line3"></div>
    </div>
    <div class="nav-bar">
      <div class="nav-links">
        <ul class="nav-list">
          <li class="nav-list-item"><%= link_to  "How it works", how_it_works_path, class:"button button-clear" %></li>
          <li class="nav-list-item"><%= link_to  "Pricing", pricing_path, class:"button button-clear" %></li>
          <li class="nav-list-item"><%= link_to  "Updates", :root, class:"button button-clear" %></li>
          <li class="nav-list-item"><%= link_to  "Support", support_path, class:"button button-clear" %></li>
        </div>
        <div class="nav-devise">
          <% if user_signed_in? %>
            <li class="nav-list-item"><%= link_to "Log out", destroy_user_session_path, class:"button button-clear", method: :delete%></li>
          <% else %>
            <li class="nav-list-item"><%= link_to  "Log in", new_user_session_path, class:"button button-clear"%></li>
            <li class="nav-list-item"><%= link_to  "Sign up",  new_user_registration_path, class:"button button-outline"%></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<div id="navbar">
  <div class="nav-wrapper">
    <%# Logo link to home %>
    <%= link_to :root, id:"link-home" do %>
      <%= image_tag "logo.png", class:"navbar-logo" %>
    <% end %>
    <%# navigation links %>
    <div class="nav-links">
      <%= link_to  "How it works", how_it_works_path, class:"button button-clear" %>
      <%= link_to  "Pricing", pricing_path, class:"button button-clear" %>
      <%= link_to  "Updates", :root, class:"button button-clear" %>
      <%= link_to  "Support", support_path, class:"button button-clear" %>
    </div>
    <%# Authentification link %>
    <div class="nav-devise">
      <% if user_signed_in? %>
        <%= link_to "Log out", destroy_user_session_path, class:"button button-clear", method: :delete%>
      <% else %>
        <%= link_to  "Log in", new_user_session_path, class:"button button-clear"%>
        <%= link_to  "Sign up",  new_user_registration_path, class:"button button-outline"%>
      <% end %>
    </div>
  </div>
</div>